[
    uuid(5f04e7bb-8128-4f65-847c-248ea0f5c739),
    version(1.0),
    pointer_default(unique)
]
interface ServiceControl
{
    void RpcRequestStop([in] handle_t hBinding);
    long RpcGetUserInfo([in] handle_t hBinding, [out] long* isAuthenticated, [out, string] wchar_t** username);
    long RpcLogin([in] handle_t hBinding, [in, string] const wchar_t* username, [in, string] const wchar_t* password);
    long RpcLogout([in] handle_t hBinding);
    long RpcGetLicenseInfo([in] handle_t hBinding, [out] long* hasLicense, [out] long* blocked, [out, string] wchar_t** expirationDate);
    long RpcActivate([in] handle_t hBinding, [in, string] const wchar_t* activationKey);
    long RpcGetAvDatabaseInfo([in] handle_t hBinding, [out] long* isLoaded, [out, string] wchar_t** releaseDate, [out] long* recordCount);
    long RpcScanPath([in] handle_t hBinding, [in, string] const wchar_t* path, [in] long isFolder, [out] long* infected, [out, string] wchar_t** summary);
}
